services:
  steampipe:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        plugin-src: ../steampipe-plugin-instana
    container_name: steampipe
    volumes:
      - ./queries:/home/steampipe/queries
    environment:
      - STEAMPIPE_LOG_LEVEL=TRACE
      - INSTANA_API_TOKEN
      - INSTANA_ENDPOINT_URL
    command: bash -c "rm -f /home/steampipe/.steampipe/internal/*.pid /home/steampipe/.steampipe/internal/*.lock 2>/dev/null; steampipe service start --foreground"
    env_file:
      - .env
    ports:
      - 9193:9193
    restart: unless-stopped
